/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QRQkcTvrqAV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"

export function sub() {
  return (
    <div className="flex h-screen flex-col">
      <header className="bg-gray-900 py-4 px-6 text-white">
        <h1 className="text-2xl font-bold">Mental Health Support AI</h1>
      </header>
      <main className="flex-1 overflow-y-auto p-6">
        <div className="space-y-4">
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-gray-500 dark:text-gray-400">
              Hello, I'm here to provide support and guidance for your mental health. How are you feeling today?
            </p>
          </div>
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-gray-500 dark:text-gray-400">
              Based on your response, it seems like you may be feeling a bit down. That's completely normal and
              understandable. Let's take a look at some strategies that can help you feel better.
            </p>
            <div className="mt-4 flex flex-col gap-2">
              <Button variant="outline">
                <SmileIcon className="mr-2 h-4 w-4" />
                Practice Gratitude
              </Button>
              <Button variant="outline">
                <MagnetIcon className="mr-2 h-4 w-4" />
                Try Meditation
              </Button>
              <Button variant="outline">
                <ContactIcon className="mr-2 h-4 w-4" />
                Talk to a Counselor
              </Button>
            </div>
          </div>
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-gray-500 dark:text-gray-400">
              I also wanted to share some information about the importance of self-care and maintaining a healthy
              lifestyle. Taking care of your physical and mental well-being can have a significant impact on your
              overall mood and outlook.
            </p>
            <div className="mt-4">
              <LineChart className="w-full aspect-[16/9]" />
            </div>
          </div>
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-gray-500 dark:text-gray-400">
              Remember, you're not alone in this journey. I'm here to support you every step of the way. Please don't
              hesitate to reach out if you need any additional resources or just someone to talk to.
            </p>
            <div className="mt-4 flex flex-col gap-2">
              <Button variant="outline">
                <PhoneIcon className="mr-2 h-4 w-4" />
                Call a Helpline
              </Button>
              <Button variant="outline">
                <BookOpenIcon className="mr-2 h-4 w-4" />
                Read Self-Help Articles
              </Button>
              <Button variant="outline">
                <CalendarIcon className="mr-2 h-4 w-4" />
                Schedule an Appointment
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function BookOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ContactIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 18a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <circle cx="12" cy="10" r="2" />
      <line x1="8" x2="8" y1="2" y2="4" />
      <line x1="16" x2="16" y1="2" y2="4" />
    </svg>
  )
}


function LineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


function MagnetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 15-4-4 6.75-6.77a7.79 7.79 0 0 1 11 11L13 22l-4-4 6.39-6.36a2.14 2.14 0 0 0-3-3L6 15" />
      <path d="m5 8 4 4" />
      <path d="m12 15 4 4" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}
